services:
  postgres:
    image: postgres:15-alpine
    container_name: job-queue-postgres
    environment:
      POSTGRES_DB: jobqueue
      POSTGRES_USER: jobqueue
      POSTGRES_PASSWORD: jobqueue
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobqueue"]
      interval: 5s
      timeout: 5s
      retries: 5



volumes:
  postgres_data: